name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install poetry
        run: pip install poetry==2.1.3
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run format
        run: poetry run ruff format --check .
      - name: Run lint
        run: poetry run ruff check .
      - name: Run mypy
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest -v
